export interface Plant {
  name: string;
  latin: string;
  region: string;
  care: string[];
  description: string;
  image: string;
  category: string;
}

export const plants: Plant[] = [
  {
    name: 'Narra',
    latin: 'Pterocarpus indicus',
    region: 'Philippines (native, Southeast Asia)',
    care: ['low care', 'slow growing'],
    description: 'The national tree of the Philippines, known for its durable hardwood and golden-yellow flowers.',
    image: '/narra.jpg',
    category: 'Native Trees',
  },
  {
    name: 'Molave',
    latin: 'Vitex parviflora',
    region: 'Philippines (endemic)',
    care: ['low care', 'slow growing'],
    description: 'A strong, termite-resistant native tree ideal for long-term reforestation projects.',
    image: '/molave.jpg',
    category: 'Native Trees',
  },
  {
    name: 'Yakal',
    latin: 'Shorea astylosa',
    region: 'Philippines (endemic)',
    care: ['medium care', 'slow growing'],
    description: 'A dense and heavy hardwood species native to Luzon and Mindanao, used in construction.',
    image: '/yakal.jpg',
    category: 'Native Trees',
  },
  {
    name: 'Lauan (Red)',
    latin: 'Shorea negrosensis',
    region: 'Philippines (native)',
    care: ['medium care', 'slow growing'],
    description: 'A group of native trees valuable for their timber and reforestation use.',
    image: '/lauan_red.jpg',
    category: 'Native Trees',
  },
  {
    name: 'Ipil',
    latin: 'Intsia bijuga',
    region: 'Southeast Asia and Pacific (native in PH)',
    care: ['low care', 'slow growing'],
    description: 'A hardwood species used in high-quality furniture and reforestation.',
    image: '/ipil.jpg',
    category: 'Native Trees',
  },
  {
    name: 'Bagras',
    latin: 'Eucalyptus deglupta',
    region: 'Philippines (Mindanao, native)',
    care: ['low care', 'fast growing'],
    description: 'Also known as rainbow eucalyptus, it’s grown for pulpwood and ornamental value.',
    image: '/bagras.jpg',
    category: 'Native Trees',
  },
  {
    name: 'Mango',
    latin: 'Mangifera indica',
    region: 'Tropical Asia (widely grown in PH)',
    care: ['medium care', 'medium growing'],
    description: 'A popular fruit tree producing sweet mangoes; used in agroforestry and backyard planting.',
    image: '/mango.jpg',
    category: 'Fruit-Bearing Trees',
  },
  {
    name: 'Lanzones',
    latin: 'Lansium domesticum',
    region: 'Southeast Asia (cultivated in PH)',
    care: ['medium care', 'medium growing'],
    description: 'A tropical fruit tree producing clusters of sweet fruits; popular in Mindanao.',
    image: '/lanzones.jpg',
    category: 'Fruit-Bearing Trees',
  },
  {
    name: 'Durian',
    latin: 'Durio zibethinus',
    region: 'Southeast Asia (cultivated in PH)',
    care: ['high care', 'medium growing'],
    description: 'Known as the “king of fruits,” durian trees are planted in southern Philippines.',
    image: '/durian.jpg',
    category: 'Fruit-Bearing Trees',
  },
  {
    name: 'Rambutan',
    latin: 'Nephelium lappaceum',
    region: 'Southeast Asia (cultivated in PH)',
    care: ['medium care', 'medium growing'],
    description: 'Produces hairy red fruits with sweet flesh; widely planted in fruit farms.',
    image: '/rambutan.jpg',
    category: 'Fruit-Bearing Trees',
  },
  {
    name: 'Coconut',
    latin: 'Cocos nucifera',
    region: 'Tropical regions (native in PH)',
    care: ['low care', 'slow growing'],
    description: 'A versatile palm tree that produces coconuts; important in Philippine economy.',
    image: '/coconut.jpg',
    category: 'Fruit-Bearing Trees',
  },
  {
    name: 'Calamansi',
    latin: 'Citrus microcarpa',
    region: 'Philippines (widely cultivated)',
    care: ['medium care', 'medium growing'],
    description: 'A small citrus fruit tree valued for its fruit and as an ornamental plant.',
    image: '/calamansi.jpg',
    category: 'Fruit-Bearing Trees',
  },
  {
    name: 'Mahogany',
    latin: 'Swietenia macrophylla',
    region: 'Central/South America (introduced)',
    care: ['low care', 'fast growing'],
    description: 'Popular for timber but controversial for biodiversity impact in native forests.',
    image: '/mahogany.jpg',
    category: 'Fast-Growing Trees',
  },
  {
    name: 'Gmelina',
    latin: 'Gmelina arborea',
    region: 'South/Southeast Asia',
    care: ['low care', 'fast growing'],
    description: 'Fast-growing tree used for timber and reforestation; thrives in lowland areas.',
    image: '/gmelina.jpg',
    category: 'Fast-Growing Trees',
  },
  {
    name: 'Acacia',
    latin: 'Acacia mangium',
    region: 'Australia/Southeast Asia (introduced)',
    care: ['low care', 'fast growing'],
    description: 'Hardy nitrogen-fixing tree used in degraded land rehabilitation and wood production.',
    image: '/acacia.jpg',
    category: 'Fast-Growing Trees',
  },
  {
    name: 'Ipil-ipil',
    latin: 'Leucaena leucocephala',
    region: 'Central America (introduced)',
    care: ['low care', 'very fast growing'],
    description: 'Small tree used for erosion control and fodder, though can be invasive.',
    image: '/ipil_ipil.jpg',
    category: 'Fast-Growing Trees',
  },
  {
    name: 'Bamboo (Kawayang Tinik)',
    latin: 'Bambusa blumeana',
    region: 'Philippines (native)',
    care: ['low care', 'very fast growing'],
    description: 'A native bamboo species used for furniture, construction, and erosion control.',
    image: '/kawayang_tinik.jpg',
    category: 'Fast-Growing Trees',
  },
  {
    name: 'Bakhaw',
    latin: 'Rhizophora mucronata',
    region: 'Coastal Philippines and SE Asia',
    care: ['medium care', 'medium growing'],
    description: 'A mangrove tree used in coastal rehabilitation; supports marine life and prevents erosion.',
    image: '/bakhaw.jpg',
    category: 'Mangrove Species',
  },
  {
    name: 'Pagatpat',
    latin: 'Sonneratia alba',
    region: 'Coastal Philippines',
    care: ['medium care', 'medium growing'],
    description: 'Mangrove species with broad leaves; helps stabilize muddy shorelines.',
    image: '/pagatpat.jpg',
    category: 'Mangrove Species',
  },
  {
    name: 'Nipa Palm',
    latin: 'Nypa fruticans',
    region: 'Coastal Philippines (native)',
    care: ['low care', 'slow growing'],
    description: 'A mangrove palm used in roofing and vinegar production.',
    image: '/nipa.jpg',
    category: 'Mangrove Species',
  },
  {
    name: 'Fire Tree',
    latin: 'Delonix regia',
    region: 'Tropical regions (introduced)',
    care: ['low care', 'fast growing'],
    description: 'Ornamental tree with bright red-orange flowers, popular in urban landscaping.',
    image: '/firetree.jpg',
    category: 'Urban/Ornamental Trees',
  },
  {
    name: 'Balete',
    latin: 'Ficus benjamina',
    region: 'Tropical Asia (native in PH)',
    care: ['medium care', 'medium growing'],
    description: 'Sacred fig tree often found in plazas and parks; has spiritual significance.',
    image: '/balete.jpg',
    category: 'Urban/Ornamental Trees',
  },
  {
    name: 'Neem Tree',
    latin: 'Azadirachta indica',
    region: 'South Asia (introduced)',
    care: ['low care', 'fast growing'],
    description: 'Known for its insect-repelling properties and medicinal uses.',
    image: '/neem.jpg',
    category: 'Urban/Ornamental Trees',
  },
  {
    name: 'Royal Palm',
    latin: 'Roystonea regia',
    region: 'Tropical Americas (introduced)',
    care: ['medium care', 'medium growing'],
    description: 'Tall, stately palm tree often planted along roads and gardens.',
    image: '/royalpalm.jpg',
    category: 'Urban/Ornamental Trees',
  },
];
